# Make Thy Own Markov Chains

With all the math thrown at you, you may think that building a Markov chain would be extremely painful. In actuality, it is simpler than you think, and there are MULTIPLE ways to do it. We are going to implement an autocomplete program for Shakespeare's works. Let us walk through the progress of doing so.

## Act I: Setting Up The Scene

This should be a given, but we got to import the packages we may need in order to get this to work. Before running the imports, make sure to set up the environment using the requirements files. To install the neccessary packages, just simply write the command in the terminal.  

pip install -r requirements.txt

Afterwards, run the following block of code to ensure everything is installed properly.

In [1]:
import os
from collections import defaultdict
import random
import numpy as np

Confirm that you are in the right directory by running the code block below. It should end with 'shakespeare-generator'.

In [2]:
print(os.getcwd())

C:\Users\randy\Productivity\shakespeare-generator-answers


Now let's double-check to see if all of our data is there.

In [3]:
os.listdir('data')

['1henryiv.txt',
 '1henryvi.txt',
 '2henryiv.txt',
 '2henryvi.txt',
 '3henryvi.txt',
 'allswell.txt',
 'asyoulikeit.txt',
 'cleopatra.txt',
 'comedy_errors.txt',
 'coriolanus.txt',
 'cymbeline.txt',
 'hamlet.txt',
 'henryv.txt',
 'henryviii.txt',
 'john.txt',
 'julius_caesar.txt',
 'lear.txt',
 'lll.txt',
 'macbeth.txt',
 'measure.txt',
 'merchant.txt',
 'merry_wives.txt',
 'midsummer.txt',
 'much_ado.txt',
 'othello.txt',
 'pericles.txt',
 'richardii.txt',
 'richardiii.txt',
 'romeo_juliet.txt',
 'taming_shrew.txt',
 'tempest.txt',
 'timon.txt',
 'titus.txt',
 'troilus_cressida.txt',
 'twelfth_night.txt',
 'two_gentlemen.txt',
 'winters_tale.txt']

oh

There is no data.

Let's quickly learn how to collect the data we would need in the first place.

### Aside: Scrape Thy Data From the Hands of Shakespeare

In order to do this, we will go back to the presentation and then head over to scraper.py to test your knowledge.

Now we shall check our data's prescence once again.

In [4]:
os.listdir('data')

['1henryiv.txt',
 '1henryvi.txt',
 '2henryiv.txt',
 '2henryvi.txt',
 '3henryvi.txt',
 'allswell.txt',
 'asyoulikeit.txt',
 'cleopatra.txt',
 'comedy_errors.txt',
 'coriolanus.txt',
 'cymbeline.txt',
 'hamlet.txt',
 'henryv.txt',
 'henryviii.txt',
 'john.txt',
 'julius_caesar.txt',
 'lear.txt',
 'lll.txt',
 'macbeth.txt',
 'measure.txt',
 'merchant.txt',
 'merry_wives.txt',
 'midsummer.txt',
 'much_ado.txt',
 'othello.txt',
 'pericles.txt',
 'richardii.txt',
 'richardiii.txt',
 'romeo_juliet.txt',
 'taming_shrew.txt',
 'tempest.txt',
 'timon.txt',
 'titus.txt',
 'troilus_cressida.txt',
 'twelfth_night.txt',
 'two_gentlemen.txt',
 'winters_tale.txt']

Hurrah! Our data directory is plentiful. Now to begin the Markov chain creation process.

## Act II: Sentencing Thy Text Into Chains

Now given large amounts of texts, let's make it digestable if we split all of it into sentences.

**_TODO_**: _We need a way to extract the sentences from all the text given to us. Let us be bold and do so FROM SCRATCH! But first we need to set some requirements/steps in order for us to be on the same page._

1. Iterate through every text file in our newly created data folder.
2. Open each text file and read all the text at once.
3. To normalize the sentences, we replace every whitespace with a space and every ending punctuation with a period. (We will still maintain the commas and semicolons and such for now.)
4. Split by period.

**Replacing standards**
1. ['\r', '\n', '\t', '-'] -> ' '
2. ['?', '!'] -> '.'

**Hints**
1. os.listdir(dir: str) -> List[str] = Retrieves a list of files found within the directory. (Used above)
2. s.split(char: str) -> List[str] = Splits s by a char and gives you a list of all segments from the split
3. s.replace(old, new) -> str = Replaces every instance of old with new in s
4. l1.extends(l2) -> Appends all the elements from l2 to l1
5. with open(file, 'r') as f: = Open the file as f in for the purposes of reading it

In [5]:
sentences = list()
n = 10 # Feel free to play around with this value.

for text in os.listdir('data')[:5]:
    with open('data/' + text, 'r') as f:
        data = f.read()
        clean = data.replace('\r', ' ').replace('\n', ' ').replace('-', ' ').replace('\t', ' ').replace('?', '.').replace('!', '.').split(".")
        sentences.extend(clean)

_Note: For the purposes of this workshop, only take a small subset of the files or even just one file in the data folder. Setting up a Markov chain for all the data would take an extremely long time. If you have time, you can run the entire folder in your own time._

After writing your function, let's see the sentences we have created by running the code block below.

In [6]:
sentences = [s.strip() for s in sentences]
print(f"First {n} sentences")
print("------------------------")
for num, sent in enumerate(sentences[:n], 1):
    print(f"{num}) {sent}.")

First 10 sentences
------------------------
1) Enter KING HENRY, LORD JOHN OF LANCASTER, the EARL of WESTMORELAND, SIR WALTER BLUNT, and others  So shaken as we are, so wan with care, Find we a time for frighted peace to pant, And breathe short winded accents of new broils To be commenced in strands afar remote.
2) No more the thirsty entrance of this soil Shall daub her lips with her own children's blood; Nor more shall trenching war channel her fields, Nor bruise her flowerets with the armed hoofs Of hostile paces: those opposed eyes, Which, like the meteors of a troubled heaven, All of one nature, of one substance bred, Did lately meet in the intestine shock And furious close of civil butchery Shall now, in mutual well beseeming ranks, March all one way and be no more opposed Against acquaintance, kindred and allies: The edge of war, like an ill sheathed knife, No more shall cut his master.
3) Therefore, friends, As far as to the sepulchre of Christ, Whose soldier now, under whose b

Huzzah! We have our sentences. Now we shall build our markov chains using not one, but TWO different ways.

## Act III: Lord Ihler's and His Matrix Servant

Professor Alexander Ihler is one of our advisors here for AI@UCI. He is currently teaching CS 179, which is a class about graphical models, where different variables express their dependencies to each other in the form of a graph. One graphical model that has been discussed are Markov chains (woah, we're doing a workshop on this). Like what we talked about earlier, we can represent our Markov chain with a transition matrix, which is a matrix of probabilities to get from one state to another. Let's see how we can use our knowledge to create one here. Once again, from scratch.

First of all let's create a list of tokens. A token is a small unit of a piece of text and is essential in Natural Language Processing, a branch of AI. For our purposes, a token will be a word in the text.

**_TODO_**: _Let us create a list of tokens based on the sentences list that we have created earlier._

1. Iterate through each sentence
2. Remove any excess punctuation [',', ';', ':'] and replace them with a space
3. Split the sentence into tokens (tokenization) and ensure that each token is lowercase
4. Filter out the non alphanumeric tokens
5. Add those tokens into our token list (maintaining their order - this is very important)

**Hints**
1. s.lower() -> str = Returns a lowercase version of the string s
2. s.isalpha() -> bool = Returns a boolean that indicates if a value is alphanumeric
3. filter(function, l) -> l2 = Returns a filtered list l2 where it only contains elements e in l where function(e) is True
3. Previous hints given before can also help

In [7]:
tokens = list()
for s in sentences:
    clean_s = s.lower().replace(',', ' ').replace(';', ' ').replace(':', ' ').split()
    clean_s = filter(lambda x: x.isalpha(), clean_s)
    tokens.extend(clean_s)

_**Theory Review**_: _What will be the size of our transition matrix?_

**Hints**  
1. np.unique(a) -> unique_elem, counts = Given an np.array, it returns an array of unique elements and their counts. Both are np.arrays
2. You might also want to make a list of unique elements as well, we will need them soon :)

In [8]:
# Write your answer here (show your work), your answer should be stored in a 2-tuple (row, col)
unq_tokens = list(np.unique(tokens))
unq = len(np.unique(tokens))
size = (unq,unq)
print(size)

(8943, 8943)


_Note: Depending on which subset of the data you have gotten, you may have different answers from everyone else. As long as you follow the correct process and have correct reasoning, you would be correct._

Now that you have a list of tokens, you can now create a transition matrix. So let's do that.

**_TODO_**: _Let us create a transition matrix to represent our Markov chain._

1. Initialize our transition matrix with a numpy matrix of zeros of size size (your theory answer comes in handy doesn't it)
2. Initialize the first term (arrow) with the first word
3. Populate the matrix while iterating through our token list
4. Normalize the probabilities in each column

**Hints**
1. np.zeros(size) -> np.array = Creates a matrix of size size (2-value tuple) filled with 0s
2. l.index(e) -> x = Returns the index x of element e in the list l
3. M[i,:] -> Row[i] = Gathers all the elements from row i
4. Operations on rows or columns will distribute to all elements in it (Ex. Row[i] += 1 will add one to every element in row i)
5. sum(iterable) -> int/float = Sums up every element in an iterable (list, tuple)
6. Remember the list of unique tokens you made from the theory question? :D

In [9]:
# Write your TODO here
T = np.zeros(size)
start = tokens[0]
for t in tokens[1:]:
    starting_state = unq_tokens.index(start)
    ending_state = unq_tokens.index(t)
    T[starting_state][ending_state] += 1
    start = t
for i in range(size[0]):
    T[i,:] /= sum(T[i,:])
print(T)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Now that we have our matrix, let's actually create an autocomplete and generate some text.

**_TODO_**: _Build an autocomplete or text generator using our transition matrix_

1. Initialize a start state (starting word) - Can be anything but if you dont have an idea, use "thou"
2. Have a set length n (default 10 but can be anything you want), and in each iteration choose the next word based on your current word

**Hints**
1. np.random.choice(l, p=probs) -> e = Returns a random element e from a list l with weighted probabilities probs for each element.  
_Note: len(l) == len(probs) and sum(probs) == 1_

In [10]:
start = 'thou'
n = 10

chain = [start]
for i in range(n):
    start = np.random.choice(unq_tokens, p=T[i,:])
    chain.append(start)
generated_text = ' '.join(chain)

Now see the gifts of your work by running the code block below and have fun by rerunning the code block above. It's not going to generate the same string everytime (unless you set a seed).

In [11]:
print(generated_text)

thou friend our all if war their with what people to


## Act IV: King Yurichev, His Library of Dictionaries and N of His Grams

Dennis Yurichev is a computer scientist who wrote "Reverse Engineering for Beginners". He wrote a blog post about creating a Markov chain autocomplete based on a given text. The theory of Markov chains is still present in this implementation. However, his approach is different from Ihler's as he uses dictionaries of dictionaries of counts rather than forming a transition matrix in order to generate words. We will look at his implementation as a review of the concepts used from the last act.

Run the code block below to setup and get started on the next act.

In [12]:
def print_stat(t, n=5):
    total=float(sum(t.values()))
    s=sorted(t.items(), key=lambda item: item[1], reverse=True)
    for pair in s[:n]:
        print ("%s %d%%" % (pair[0], (float(pair[1])/total)*100))

first=defaultdict(lambda: defaultdict(int)) # single word keys (Ex. "to")
second=defaultdict(lambda: defaultdict(int)) # two word phrases as keys (Ex. "to be")
third=defaultdict(lambda: defaultdict(int)) # three word phrases as keys (Ex. "not to be")

# Sample example of what first could be
# {"to": {"be": 1, "meet": 1}, "or": {"not": 1}}

**_TODO_**: _Let's update his dictionaries by filling our his update_occ function, and then populating the dictionary with connections and weights needed._

**Hints**
1. Each dictionary (first, second, third) is in the form {phrase: {next_word: count}}
2. Use the last 1, 2 or 3 words to create the phrase

In [13]:
def update_occ(d, seq, w):
    """
    Params:
        d: dict - Dictionary to be updated
        seq: str - The sequence that represents the previous state
        w: str - The words that represent the current state
    Returns:
        None
    
    This function updates the dictionary's count during token iteration
    """
    # Fill out function implementation here
    d[seq][w] += 1

for s in sentences:
    words = s.replace(',', ' ').replace(';', ' ').replace(":", ' ').split() # TODO: Split each sentence into words
    words = list(filter(lambda x: x.isalpha(), words))
    if len(words)==0:
        continue
    for i in range(len(words)):
        # only two words available:
        if i>=1:
            update_occ(first, words[i-1], words[i]) #TODO: update the occurences -> {"to": {"be": 1}}
        # three words available:
        if i>=2:
            update_occ(second, words[i-2] + " " + words[i-1], words[i]) #TODO: update the occurences -> {"to be": {"or": 1}}
        # four words available:
        if i>=3:
            update_occ(third, words[i-3] + " " + words[i-2] + " " + words[i-1], words[i]) #TODO: update the occurences -> {"not to be": {"that": 1}}

Test your code by running the block below. You can change test to any phrase you would want

In [14]:
test = "her sight did"
test_words=test.split(" ")

test_len=len(test_words)
last_idx=test_len-1

if test_len>=3:
    tmp=test_words[last_idx-2]+" "+test_words[last_idx-1]+" "+test_words[last_idx]
    if tmp in third:
        print ("* third order. for sequence:",tmp)
        print_stat(third[tmp])

if test_len>=2:
    tmp=test_words[last_idx-1]+" "+test_words[last_idx]
    if tmp in second:
        print ("* second order. for sequence:", tmp)
        print_stat(second[tmp])

if test_len>=1:
    tmp=test_words[last_idx]
    if tmp in first:
        print ("* first order. for word:", tmp)
        print_stat(first[tmp])
print ("")

* second order. for sequence: sight did
ravish 100%
* first order. for word: did
not 6%
he 5%
I 5%
you 4%
but 2%



Now let us complete his autocomplete. It will be a similar process to what we have done before.

**_TODO_**: _Let's finish his selection function and use it to put recreate his autocomplete algorithm._

1. Finish the gen_random_from_tbl function
2. Fill out the missing pieces of the for loop for text generation using gen_random_from_tbl

**Hints**
1. random.choices(l, weights=w) -> e = Returns a random element e from a list l with weights/bias w  
_Note: len(l) == len(w) but sum(w) not necessariliy equal to 1_
2. Use the last 1, 2 or 3 words to create the phrase

In [15]:
text = ['upon', 'whose', 'majesty']

def gen_random_from_tbl(t):
    """
    Params:
        d: dict - Dictionary whose value we are taking from. It should be in the form {word (str): weight (int)}
    Returns:
        str - Random word generated from d
        
    Given a dictionary with word-weight pairs, generate a random word from the dictionary and return it.
    """
    # TODO: Complete the function (Can you do it in one line?)
    return random.choices(list(t.keys()), weights=list(t.values()))[0]

text_len=len(text)

# generate at most 100 words:
for i in range(200):
    last_idx=text_len-1
    tmp3= text[last_idx-2] + " " + text[last_idx-1] + " " + text[last_idx] #TODO: Create 3 word phrase using last_idx
    tmp2= text[last_idx-1] + " " + text[last_idx] #TODO: Create 2 word phrase using last_idx
    tmp1= text[last_idx] #TODO: Create 1 word phrase using last_idx
    if tmp3 in third:
        new_word=gen_random_from_tbl(third[tmp3]) #TODO: Generate a new word
    elif tmp2 in second:
        new_word=gen_random_from_tbl(second[tmp2]) #TODO: Generate a new word
    elif tmp1 in first:
        new_word=gen_random_from_tbl(first[tmp1]) #TODO: Generate a new word
    else:
        break # dead end
    text.append(new_word)
    text_len=text_len+1

print (" ".join(text))

upon whose majesty That Cardinal Beaufort is at point of death For suddenly a grievous sickness took him That makes him close his eyes and methought he had made two holes in the ale new petticoat and so peeped through force of your report My noble Lord of Suffolk or for that My tender youth was never yet attaint With any passion of inflaming love I cannot tell but this I am assured I feel such sharp dissension in my breast And what I do A witch by fear not force like Hannibal Drives back our troops and conquers as she lists So bees with smoke and doves with noisome stench Are from their hives and houses driven away what instinct hadst thou for it straight a thing impossible To compass wonders but by help of devils and hell have through the very middest of you grant that my poor virtue grant that words bewitch him not come here no by my faith I think you are fallen into the disease for you hear not what I did I did in honour Led by the impartial conduct of my soul And till I root out th

## Act V: Conclusion

As you may have seen, although Ihler's and Yurichev's used different implementation, the basic idea of Markov chains are the same. Now in a discussion format all together, let's answer the following questions.

1. What are the similarities between Ihler's and Yurichev's implementations?
2. What are the differences between Ihler's and Yurichev's implementations?
3. Which implementation would you prefer and why?

Thank you for attending this workshop, and I hope you left this knowing something new.

## Exeunt